### ISSUE TITLE
Some new Ideas for you Guys

### ISSUE THREAD

**Issue by Miguel7373** [Alchaph/SoundScore#180]
1. Album: You can add albums to add like a bundle of songs.

2. Tags: You can add Tags to posts so you can search for a specific type of post.

3. Tagging Users: You can tag users who have an account to make commenting more efficient.

**Comment by nevio18324** [comment]
L Ideas

**Comment by Miguel7373** [comment]
Wow, this behavior is really bad with people like this in projects that will definitely flop

**Comment by Miguel7373** [comment]
wow Closing an issue without even implementing any of them cool team you got there
